#!/usr/bin/env python3
"""Build the two go2_description-derived MuJoCo worlds (original / mirror-symmetrized) + flat scenes, convert the
COLLADA visual meshes to STL on the data root, and write the provenance manifest.

    python scripts/build_go2_urdf_worlds.py            # writes src/geofdi/sim/assets/go2_urdf/mjcf/*.xml,
                                                        #        assets/go2_urdf/PROVENANCE.json,
                                                        #        $GEOFDI_DATA_ROOT/data/assets/go2_urdf/meshes_stl/*.stl

Numbers: everything from urdf/go2_description.urdf; joint dynamics from xacro/const.xacro (damping 0.01, friction
0.2); armature 0.01 (menagerie); foot contact / keyframe / sensors as in the S0 world (go2_sym.xml).
"""
from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path

import mujoco
import numpy as np

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "src"))
from geofdi.sim.urdf2mjcf import ConvertOptions, convert, sha256_of   # noqa: E402

ASSETS = REPO / "src" / "geofdi" / "sim" / "assets" / "go2_urdf"
URDF = ASSETS / "urdf" / "go2_description.urdf"
MJCF = ASSETS / "mjcf"
HOME_QPOS = (0, 0, 0.27, 1, 0, 0, 0) + (0, 0.9, -1.8) * 4
HOME_CTRL = (0, 0.9, -1.8) * 4


def scene_xml(model_file: str, name: str) -> str:
    return (f'<mujoco model="{name} flat scene (headless)">\n'
            f'  <!-- Flat-ground scene for GeoFDI simulation (go2_description-derived world). -->\n'
            f'  <include file="{model_file}"/>\n'
            f'  <worldbody>\n    <geom name="floor" size="0 0 0.05" type="plane" friction="0.8 0.02 0.01"/>\n  </worldbody>\n</mujoco>\n')


def main():
    MJCF.mkdir(exist_ok=True)
    common = dict(joint_damping=0.01, joint_frictionloss=0.2, joint_armature=0.01, keyframe_qpos=HOME_QPOS, keyframe_ctrl=HOME_CTRL)
    variants = {
        "go2_urdf": ConvertOptions(model_name="go2_urdf", **common),
        "go2_urdf_sym": ConvertOptions(model_name="go2_urdf_sym", sym_base_inertia=True, sym_leg_collisions="left", **common),
    }
    header = ("<!-- {name}.xml — generated by scripts/build_go2_urdf_worlds.py from assets/go2_urdf/urdf/go2_description.urdf\n"
              "     (Unitree go2_description, BSD; sha256 {h}). Headless: collision primitives only, explicit URDF inertials\n"
              "     (fullinertia), torque motors with URDF effort limits, IMU site from the URDF 'imu' link, S0 sensors/keyframe.\n"
              "     {note} -->\n")
    notes = {"go2_urdf": "ORIGINAL: base ixy=1.2166e-4, iyz=-3.12e-5 kept; FL calf collision cylinder as in the URDF (r 0.012 vs 0.013 elsewhere).",
             "go2_urdf_sym": "SYMMETRIZED about y=0: base I <- (I+EIE)/2 (ixy=iyz=0), com_y=0; left-leg collision primitives = mirror of the right ones (FL calf cylinder r 0.013). Inertials of the legs are exact mirrors in the URDF already."}
    out = {}
    for name, opts in variants.items():
        xml = convert(URDF, opts)
        xml = header.format(name=name, h=sha256_of(URDF)[:16], note=notes[name]) + xml
        (MJCF / f"{name}.xml").write_text(xml + "\n")
        (MJCF / f"scene_{name}.xml").write_text(scene_xml(f"{name}.xml", name))
        m = mujoco.MjModel.from_xml_path(str(MJCF / f"scene_{name}.xml"))
        out[name] = {"nbody": m.nbody, "njnt": m.njnt, "nu": m.nu, "ngeom": m.ngeom, "total_mass": float(m.body_subtreemass[1]),
                     "sha256": sha256_of(MJCF / f"{name}.xml")}
        print(name, out[name])
    # meshes: dae -> stl on the data root (visual only; not referenced by the headless MJCF)
    stl_dir = Path(os.environ["GEOFDI_DATA_ROOT"]) / "data" / "assets" / "go2_urdf" / "meshes_stl" if os.environ.get("GEOFDI_DATA_ROOT") else None
    mesh_records = {}
    for dae in sorted((ASSETS / "meshes").glob("*.dae")):
        rec = {"sha256": sha256_of(dae), "bytes": dae.stat().st_size}
        if stl_dir is not None:
            stl_dir.mkdir(parents=True, exist_ok=True)
            try:
                import trimesh
                mesh = trimesh.load(str(dae), force="mesh")
                stl = stl_dir / (dae.stem + ".stl"); mesh.export(str(stl))
                rec.update({"stl": str(stl.relative_to(Path(os.environ["GEOFDI_DATA_ROOT"]))), "stl_sha256": sha256_of(stl),
                            "vertices": int(mesh.vertices.shape[0]), "faces": int(mesh.faces.shape[0]), "extents_m": [float(x) for x in mesh.extents]})
            except Exception as e:                       # noqa: BLE001
                rec["stl_error"] = repr(e)
        mesh_records[dae.name] = rec
    prov = {"source": "Go2_URDF.zip (Unitree go2_description ROS package, SolidWorks-to-URDF export 2023-10-11), user upload 2026-08-15",
            "source_zip_sha256": "690d6863813cd2854c90e0afef3cc8102e3613c91e8f53e4850b85be916852c5",
            "license": "BSD (package.xml <license>BSD</license>; Unitree publishes go2_description under BSD-3-Clause)",
            "urdf_sha256": sha256_of(URDF), "worlds": out, "meshes": mesh_records,
            "dropped_from_zip": [".history/ (editor backups)", "dae/ (byte-identical duplicates of meshes/, base.dae == trunk.dae)", "launch/ (rviz/gazebo)"],
            "git": subprocess.run(["git", "rev-parse", "HEAD"], capture_output=True, text=True, cwd=REPO).stdout.strip()}
    (ASSETS / "PROVENANCE.json").write_text(json.dumps(prov, indent=1))
    print("wrote", ASSETS / "PROVENANCE.json")


if __name__ == "__main__":
    main()
